name: Website AutoCheck

on:
  schedule:
    - cron: '0 12 * * *'   # 8 AM ET
    - cron: '0 16 * * *'   # 12 PM ET
    - cron: '0 22 * * *'   # 6 PM ET
  workflow_dispatch:

jobs:
  run-autocheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome 124
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.207-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_124.0.6367.207-1_amd64.deb

      - name: Install matching ChromeDriver 124
        run: |
          wget -q -O chromedriver.zip "https://chromedriver.storage.googleapis.com/124.0.6367.207/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autocheck
        run: python autocheck.py
