name: Website AutoCheck

on:
  schedule:
    - cron: '0 12 * * *'   # 8 AM ET
    - cron: '0 16 * * *'   # 12 PM ET
    - cron: '0 22 * * *'   # 6 PM ET
  workflow_dispatch:

jobs:
  run-autocheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autocheck
        run: python autocheck.py
